apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-{{ .Release.Name }}-configmap
data:
  environment: {{ .Values.environment | quote }}
  envShort: {{ template "envShort" . }} 
  {{- range .Values.configData }}
  {{- if .enabled }}
  {{ .key }}: {{ .value | quote }}
  {{- end }}
  {{- end }}