targets:
  - name: production
    args:
      environment: production
      environmentType: prod

  - name: staging
    args:
      environment: staging
      environmentType: non-prod

args:
  - name: environment
  - name: environmentType

discriminator: kluctl-{{ target.name }}
