version: "3"

tasks:
  helm-pull:
    cmds:
      - kluctl helm-pull
    desc: "Pre-pull helm charts"

  render-staging:
    cmds:
      - kluctl render -t staging --print-all
    desc: "Render resource yaml with staging values"

  render-production:
    cmds:
      - kluctl render -t staging --print-all
    desc: "Render resource yaml with production values"
