apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      name: manual
  # storageClassName: local-storage
  storageClassName: standard
