apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  # storageClassName: local-storage
  storageClassName: standard
