version: "3"

tasks:
  deploy-traefik:
    desc: "Deploy Traefik using Helm"
    cmds:
      - helm repo add traefik https://traefik.github.io/charts
      - helm upgrade --install -n traefik --create-namespace traefik traefik/traefik --version 20.8.0

  apply-ingress-config:
    desc: "Deploy IngressRoute and Traefik middleware"
    cmds:
      - "kubectl apply -f IngressRoute.yaml"
      - "kubectl apply -f Middleware.yaml"
