apiVersion: v1
kind: ConfigMap
metadata:
  name: db-migrations
  namespace: demo-app
data:
  000001_create_users_table.up.sql: |
    CREATE TABLE IF NOT EXISTS public.request (
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        api_name VARCHAR(10) NOT NULL CHECK (api_name IN ('node', 'go'))
    );

  000001_create_users_table.down.sql: |
    DROP TABLE public.request;
