version: "3"

tasks:
  install-postgres:
    desc: "Deploy PostgreSQL using direct Kubernetes manifests"
    cmds:
      - kubectl create namespace postgres --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f postgres-simple.yaml

  apply-initial-db-migration-job:
    desc: "Run init.sql script against the DB"
    cmds:
      - "kubectl apply -f Secret.db-password.yaml"
      - "kubectl apply -f Job.db-migrator.yaml"