# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: demo-app
  annotations:
    kluctl.io/hook: pre-deploy
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@postgres-postgresql.postgres.svc.cluster.local:5432/postgres
