# ⛔️ DONT PUT SECRET FILES IN VCS
apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: demo-app
  # TODO: figure out the proper way to create a secret consumed by a pre-deploy hook
  # annotations:
  #   kluctl.io/hook: pre-deploy
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:foobarbaz@cnpg-minimal-rw.postgres.svc.cluster.local:5432/postgres
