version: 3

env:
  BORDER: double
  BORDER_FOREGROUND: "212"
  PADDING: "1 1"
  MARGIN: "1 1"
  NAMESPACE: 09--cnpg

tasks:
  01-create-namespace:
    desc: "Create a namespace for these examples and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens ${NAMESPACE}

  02-install-cnpg-operator:
    desc: "Install cloudnative-pg operator"
    cmds:
      - "helm repo add cnpg https://cloudnative-pg.github.io/charts"
      - |
        helm upgrade --install cnpg \
          --namespace cnpg-system \
          --create-namespace \
          cnpg/cloudnative-pg

  03-apply-minimal-cluster:
    desc: "Apply minimal cnpg cluster definition"
    cmds:
      - kubectl apply -f Cluster.cnpg-minimal.yaml

  04-apply-cluster-with-backup-config:
    desc: "Apply cnpg cluster definition with backup configuration"
    cmds:
      - cmd: gum style "🚨 This assumes you have set up a Civo object store and placed the credentials in a secret named civo-object-store-creds! 🚨 "
        silent: true
      - kubectl apply -f Cluster.cnpg-with-backup-config.yaml
      - kubectl apply -f ScheduleBackup.yaml
      - kubectl apply -f Backup.yaml

  05-delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - cmd: gum style "🚨 Deleting the namespace recursively deletes the resources inside of it! 🚨 "
        silent: true
      - kubectl delete -f Namespace.yaml
